server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/products/**,/storagecellar/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payments/**
        - id: shipping-service
          uri: lb://shipping-service
          predicates:
            - Path=/shipping/**
